spring.application.name=demo1

spring.docker.compose.enabled=false


spring.datasource.url=jdbc:postgresql://localhost:5433/demo1
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml

spring.jpa.hibernate.ddl-auto=validate
